const API_URL = localStorage.getItem('granito_api_url') || 'http://localhost:3000/api';
const token = () => localStorage.getItem('granito_token');
export const money = (n) => new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(Number(n));
export async function api(path, options={}) { const headers={...(options.body?{'Content-Type':'application/json'}:{}),...(options.headers||{})}; if(token()) headers.Authorization=`Bearer ${token()}`; const res=await fetch(`${API_URL}${path}`, {...options,headers}); const data=await res.json().catch(()=>({})); if(!res.ok) throw new Error(data.error||'No pudimos completar la solicitud.'); return data; }
export const loggedIn=()=>Boolean(token());
export function logout(){localStorage.removeItem('granito_token');location.href='index.html'}
export async function renderNav(){const host=document.querySelector('[data-nav]');if(!host)return;let account='Iniciar sesión';let action='login.html';if(loggedIn()){try{const me=await api('/me');account=`Mi cuenta · ${money(me.saldo)}`;action='cuenta.html'}catch{localStorage.removeItem('granito_token')}}host.innerHTML=`<div class="notice">Modo de prueba: no se realizan cargos reales</div><header class="header"><nav class="wrap nav"><a class="brand" href="index.html">🌾 Granito</a><div class="nav-links"><a href="index.html">Campañas</a><a class="balance" href="${action}">${account}</a>${loggedIn()?'<button class="btn light" id="logout">Cerrar sesión</button>':''}</div></nav></header>`;document.querySelector('#logout')?.addEventListener('click',logout)}
export function escape(s=''){const e=document.createElement('div');e.textContent=s;return e.innerHTML}
export async function donate(campaign,amount,button){if(!loggedIn()){localStorage.setItem('granito_pending',JSON.stringify({campaign,amount}));location.href='login.html';return}button.disabled=true;const initial=button.textContent;button.textContent='Donando…';try{const result=await api('/donaciones',{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({campana_id:campaign,monto:amount,anonima:false})});window.dispatchEvent(new CustomEvent('donated',{detail:result}));return result}catch(error){throw error}finally{button.disabled=false;button.textContent=initial}}
